# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yuanqing
brief-intro: Evoultion Gleaning
url: "https://fengpku.github.io" # the base hostname & protocol for your site
email: yuanqingfeng@126.com
permalink: /:year/:month/:day/:title/

# other links
github_username: fengpku
linkedIn_username: yuanqing-feng-a4384477

description_footer: Small steps everyday


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6



